//! Generates the per-game constants from `games/<GAME>/game.json` before compiling.
//!
//! `GAME` selects the loader (default `madden09`); nothing in `src/` names a game, so
//! every loader in `games/` builds from this one source tree. The bundle's name, id and
//! window title come from `games/<GAME>/tauri.conf.json`, which the build scripts pass
//! to the Tauri CLI with `--config`.

use std::{env, fs, path::PathBuf};

/// Fields of game.json that become `pub const` in `crate::config`.
const FIELDS: &[(&str, &str)] = &[
    ("APP_TITLE", "title"),
    ("REPO_OWNER", "repoOwner"),
    ("REPO_NAME", "repoName"),
    ("REPO_URL", "repoUrl"),
    ("SLUS_FOLDER", "slusFolder"),
    ("SPARSE_PATH", "sparsePath"),
    ("TEMP_DIR_NAME", "tempDirName"),
];

fn main() {
    let game = env::var("GAME").unwrap_or_else(|_| "madden09".to_string());
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repo root")
        .join("games")
        .join(&game)
        .join("game.json");

    println!("cargo:rerun-if-env-changed=GAME");
    println!("cargo:rerun-if-changed={}", manifest.display());

    let text = fs::read_to_string(&manifest).unwrap_or_else(|e| {
        panic!("GAME={game}: cannot read {}: {e}\nRun `tools/games.py list` for the ids that exist.",
               manifest.display())
    });
    let json: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", manifest.display()));

    let mut out = format!(
        "// Generated by build.rs from games/{game}/game.json — do not edit.\n\
         /// The game this binary was built for.\n\
         #[allow(dead_code)]\n\
         pub const GAME_ID: &str = {:?};\n",
        game
    );
    for (konst, field) in FIELDS {
        let value = json.get(field).and_then(|v| v.as_str()).unwrap_or_else(|| {
            panic!("{} has no string field {field:?}", manifest.display())
        });
        // APP_TITLE is only read by the frontend, which gets it from Vite instead.
        if *konst == "APP_TITLE" {
            out.push_str("#[allow(dead_code)]\n");
        }
        out.push_str(&format!("pub const {konst}: &str = {value:?};\n"));
    }

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("game_config.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));

    tauri_build::build()
}
